In [1]:
a=int(input('enter number'))
b=int(input('enter number'))
def abc():
    print('good message')
print(a+b)
# dunder(__)
if __name__=='__main__':
    print("called from main")

5
called from main


In [2]:
import keyword as kw
kw.iskeyword('int')

False

In [2]:
import numpy as np
a=np.array([3,4])
a

array([3, 4])

In [3]:
import numpy as np
b=np.array([])
b

array([], dtype=float64)

In [7]:
len(a)

2

In [8]:
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('float64')

In [10]:
a.size

2

In [ ]:
a.shape

(2,)

In [11]:
a.ndim

1

In [ ]:
type(a)

numpy.ndarray

In [12]:
c=np.array([[2,3,4],[4,5,6],[7,8,9],[10,11,9]])
c

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11,  9]])

In [13]:
c.ndim


2

In [14]:
c.shape

(4, 3)

In [15]:
d=np.array([[[2],[3],[4]],[[4],[5],[6]],[[7],[8],[9]],[[10],[11],[9]]])
d.shape

(4, 3, 1)

In [16]:
e=np.array([[[2,2],[3,3],[4,4]],[[4,4],[5,5],[6,6]],[[7,7],[8,8],[9,9]],[[10,10],[11,11],[9,9]]])
e.shape

(4, 3, 2)

In [17]:
c.sum(axis=1)

array([ 9, 15, 24, 30])

In [18]:
#subscripting
c[0:2,-1]

array([4, 6])

In [19]:
c[0:2,-1:]

array([[4],
       [6]])

In [22]:
a=np.array([[5,7,8],[7,3,4]])
a

array([[5, 7, 8],
       [7, 3, 4]])

In [25]:
k=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
k
k.shape

(4, 3)

In [46]:
m=np.array([[[4,41],[8,81],[7,71]],
            [[3,31],[1,11],[5,51]],
            [[6,61],[9,91],[13,131]]])
print(m.shape)
m

(3, 3, 2)


array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [47]:
print(k[2,0:3])
print(k[2,:])
print(k[2])

[11 15 17]
[11 15 17]
[11 15 17]


In [50]:
k[:,1]
#but it is returned as a row instead of columns
print(k[:,1:2])

[[ 8]
 [ 3]
 [15]
 [31]]


In [52]:
m[1,1,1]

11

array([ 8, 81])

In [56]:
m[0:2,1:3,0]

array([[8, 7],
       [1, 5]])

In [60]:
m[2,1:3,0:2]

array([[  9,  91],
       [ 13, 131]])

In [62]:
b=np.array([[55,55,55],[7,3,4]])
b

array([[55, 55, 55],
       [ 7,  3,  4]])

In [64]:
b[0,0]=505
b

array([[505,  55,  55],
       [  7,   3,   4]])

In [65]:
b[1,:3]=[17,13,14]
b

array([[505,  55,  55],
       [ 17,  13,  14]])

In [66]:
b[:2,1]=[551,131]
b

array([[505, 551,  55],
       [ 17, 131,  14]])

In [67]:
b+3

array([[508, 554,  58],
       [ 20, 134,  17]])

In [70]:
#inserting and deleting row
np.append(b,[[1,1,1]],axis=0)#row

array([[505, 551,  55],
       [ 17, 131,  14],
       [  1,   1,   1]])

In [73]:
np.append(b,[[1],[1]],axis=1)#column

array([[505, 551,  55,   1],
       [ 17, 131,  14,   1]])

In [76]:
np.delete(b,2,axis=1)

array([[505, 551],
       [ 17, 131]])

In [77]:
b

array([[505, 551,  55],
       [ 17, 131,  14]])

In [82]:
#array creation function
np.array()
np.arange()
np.linspace()
np.ones()
np.zeros()
np.eye()
np.random.randint()

TypeError: array() missing required argument 'object' (pos 0)

In [15]:
print(np.arange(11),np.arange(1,11,1.5))
np.linspace(1,10,10)

[ 0  1  2  3  4  5  6  7  8  9 10] [ 1.   2.5  4.   5.5  7.   8.5 10. ]


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
print(np.ones([4,5]))
p=np.ones([4,5])

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.ones([4,5],dtype=int)
#type conversion
p.astype(int)
p8=p.astype('uint8')
p8

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [31]:
np.random.randint(1,100,1)
np.random.randint(1,100,[3,5])

array([[41,  5, 99, 53, 24],
       [62, 56, 31, 29, 64],
       [87, 94, 21, 24, 60]])

In [51]:
# seed will fix the randomness
np.random.seed(1982)
np.random.randint(1,100,[3,5])


array([[86, 85, 13, 58,  1],
       [87, 32, 14,  9,  1],
       [26, 86, 78, 28, 31]])

In [59]:
r=np.random.rand(3,4)

In [61]:
print(np.random.randn(3,4))


[[-0.33182854 -0.96598632  0.0615425  -2.20840431]
 [-0.58672447 -0.29211158  2.40740454 -0.3051246 ]
 [ 0.79972555 -0.03761842 -0.85329962 -0.31139024]]


In [65]:
#for loading any file
np.loadtxt('data.txt',dtype='str')

array([['this', 'is', 'a', 'new', 'file'],
       ['here', 'we', 'get', 'some', 'data']], dtype='<U4')

In [69]:
np.loadtxt('data1.txt',delimiter=',')

array([[45., 65., 78., 91.],
       [23., 19., 34., 54.],
       [ 1.,  4.,  3.,  2.]])

In [70]:
a=np.random.randint(10,1000,[3,6])
a

array([[872, 848, 432, 620, 154, 335],
       [ 68, 331, 679, 572, 446, 852],
       [487, 969, 204, 308, 420,  38]])

In [72]:
np.savetxt('data3.txt',a,delimiter='|',fmt='%d')


In [74]:
sum(sum(a))

8635

In [75]:
#numpy array sum
a.sum()

8635

In [79]:
#sum of rows
a.sum(axis=1)
####only here axis =1 means rows 

array([3261, 2948, 2426])

In [80]:
a.mean(axis=1)

array([543.5       , 491.33333333, 404.33333333])

In [81]:
a.max(axis=0)

array([872, 969, 679, 620, 446, 852])

In [84]:
a.argmax(axis=0)

array([0, 2, 1, 0, 1, 1], dtype=int64)

In [85]:
a.flatten()

array([872, 848, 432, 620, 154, 335,  68, 331, 679, 572, 446, 852, 487,
       969, 204, 308, 420,  38])

In [41]:
opencv-python
scikit-image
matplotlib

NameError: name 'opencv' is not defined

In [30]:
!python -m pip install opencv-python



[notice] A new release of pip is available: 23.0.1 -> 23.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
!python -m pip install scikit-image


[notice] A new release of pip is available: 23.0.1 -> 23.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [25]:
!python -m pip install matplotlib

     ---------------------------------------- 0.0/7.6 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.6 MB 1.4 MB/s eta 0:00:06
     ---------------------------------------- 0.1/7.6 MB 825.8 kB/s eta 0:00:10
     ---------------------------------------- 0.1/7.6 MB 880.9 kB/s eta 0:00:09
      --------------------------------------- 0.2/7.6 MB 919.0 kB/s eta 0:00:09
     - -------------------------------------- 0.2/7.6 MB 958.4 kB/s eta 0:00:08
     - -------------------------------------- 0.3/7.6 MB 1.0 MB/s eta 0:00:08
     - -------------------------------------- 0.3/7.6 MB 984.6 kB/s eta 0:00:08
     - -------------------------------------- 0.4/7.6 MB 1.0 MB/s eta 0:00:07
     -- ------------------------------------- 0.4/7.6 MB 1.0 MB/s eta 0:00:08
     -- ------------------------------------- 0.5/7.6 MB 1.0 MB/s eta 0:00:07
     -- ------------------------------------- 0.5/7.6 MB 1.1 MB/s eta 0:00:07
     -- ------------------------------------- 0.6/7.6 MB 1.1 

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.0.1 -> 23.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
